### ISSUE TITLE
Status as of now?

### ISSUE THREAD

**Issue by gima** [berneout/authors-certificate#7]
<sup>Apologies for using this issue as a kind of a question. Basing this on the usefulness to others.</sup>
## 1) Usable?

It seems that since this project is copyrighted to you, I'm not allowed to copy your AUTHORS file and use it in my project, even though you instruct how to do so in the readme's "Use" section. (I understand it like this: "This is how you commit a crime, but it's still not legal."). Based on this, I also think that the following phrase..

> Under active development. _Not yet released for widespread use._

..is done precisely to thwart people from using this (incomplete project). Am I understanding this correctly?
## 2) Status?

Last change to this project was ~4 months ago. Are you planning on completing this project? In either case, could you release this to the public in a way that it can be used is as-is and also also modified?
## 3) Wording in AUTHORS

Hopefully I'm not completely lost. I have a point I'd like to question:

**"Written permission"**

> 1. If someone else might own intellectual property in your contributions, like an employer or client, you've added their legal name in square brackets and got their **written permission** to submit your contribution.

So, I get this "written permission" from my employer to contribute their intellectual property to an opensource project. Does this permission implicitly translate to a promise not to sue? Because to my untrained eye it seems that _"Company X gives person Y the right to submit a piece of code (covered by the company's IP) to opensource project Z"_ is very different from _"[the same] with irrevocable IP license to the said piece of code (or something along those lines)"_

**Comment by rjmunro** [comment]
So this is already being used in some projects:

https://github.com/search?utf8=%E2%9C%93&q=%22The+AUTHORS+Certificate%22+filename%3AAUTHORS+-user%3Aberneout&type=Code&ref=searchresults

At time of writing, all results seem to be by one auther, @dbohdan.

I'd like something like this for projects I work on, and am wondering if using it as-is better than not using anything. I guess a question then is if the wording is changed, how can we incorporate the new wording into our projects? I've added a separate issue for that: #8.

**Comment by kemitchell** [comment]
Sorry for a late response.

I'm convinced this project is sound in its concepts, but developments and further thinking have taken my attention away form it.  From a practical point of view, I think something like [berneout-pledge](https://github.com/berneout/berneout-pledge) offers many advantages.

All work on this is greatly confused, at least for projects on GitHub, by [a recent terms of service change](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license).
