### ISSUE TITLE
Upgrading the certificate

### ISSUE THREAD

**Issue by rjmunro** [berneout/authors-certificate#8]
If the wording is changed in future, due to some legal issue or flaw, how can we incorporate the new wording into our projects?

I propose that we add the new wording at the top of the AUTHORS file, leaving the existing wording and signatures below. As people are ready, they can submit PRs to move their names from the older wording to the newer wording. Once the last one is removed, the old wording can be removed.

So until all old authors and / or their employers (as appropriate) agree, you'd have a file like:

```
# The AUTHORS Certificate
# Second edition
# ... [new wording]
Name 1 <E-Mail> (URL) [Working For]
Name 2 <E-Mail> (URL) [Working For]
...

# The AUTHORS Certificate
# First edition
# ... [old wording]
Name 3 <E-Mail> (URL) [Working For]
Name 4 <E-Mail> (URL) [Working For]
...
```

Is wording needed to make that upgrade path clear? Do we need to change "file" to something like "below section of this file"?

Alternatively, maybe we should rename the old certificate to AUTHORS-V1 or something to freeze it when a new version comes along, and add wording to the new certificate that references the old one.

**Comment by kemitchell** [comment]
Interesting.
