### ISSUE TITLE
AUTHORS interactions with DCO

### ISSUE THREAD

**Issue by cyphar** [berneout/authors-certificate#9]
From my reading (IANAL so I'm probably wrong), the DCO is more permissive than AUTHORS. In particular the first section of AUTHORS states:

> 1. All of your contributions to this project are and will be your own, original work, licensed on the same terms as this project.

But options `b)` and `c)` of the DCO explicitly allow contribution if the contributor **did not** author the project, as long as they attest they have the rights to contribute it. The ability to contribute other people's code is quite important in free software.

Section 2 seems to try to rectify the above, but it requires permissions "in writing" -- and it's not clear to me if "distributing the code to me under a free software license compatibile with this project's license" counts as "in writing".

> 2. If someone else might own intellectual property in your contributions, like an employer or client, you've added their legal name in square brackets and got their written permission to submit your contribution.

So can someone advise on whether or not this is more restrictive than the DCO or if I'm just reading it wrong?

**Comment by kemitchell** [comment]
I intended authors-certificate to require more in some circumstances than DCO.  In particular, the DCO requires more in the way of documentary evidence---_written_ permission---to submit code that someone else must license.
